### ISSUE TITLE
Skeleton Wallmarks

### ISSUE THREAD

**Issue by revolucas** [ForserX/xray-oxygen#19]
Sometimes a noticeable green square is created, what is the cause of this? I would have blamed the texture, but it occurs in a different location then the currently created wallmark. Here is a video: https://youtu.be/oB7FOjvPqdk

**Comment by ForserX** [comment]
Oh, thx. I check it later.

**Comment by revolucas** [comment]
https://postimg.org/image/n79ubclpx/

Sometimes this can happen from just a single shot on all dynamic objects.

**Comment by revolucas** [comment]
Knife creates two blood marks. This is because it shoots 2 bullets as if it was a short-ranged shotgun: https://pastebin.com/FcJMATir

But why does it only render one mark on walls, but two on bodies?

**Comment by ForserX** [comment]
@revolucas 
I'll deal with this when I rewrite the weapons classes.
