### ISSUE TITLE
x64 can't allocate enough memory

### ISSUE THREAD

**Issue by Swartz27** [ForserX/xray-oxygen#20]
Your Release->x64 configuration does not allow for proper allocation of more than 2.5-3gb or whatever the limit is. I added high resolution textures that I use in Radium to the repos gamedata folder and it will crash every time now with an error about particles. I'm not posting the error regarding particles because it's a memory limit error with nothing to do with that: it stops around 2.5-3gb every time before crashing, and removing the textures (no new particles) fixes the issue.

**Comment by ForserX** [comment]
1 GB is reserved for lua, which can cause such a problem.

**Comment by Swartz27** [comment]
I'm not sure if you mean that its a problem on my end or a problem with the code. No new scripts used and I have an absurd amount of RAM.

**Comment by ForserX** [comment]
@Swartz27, The problem is that I can not say for sure, because I do not have your resources. Probably the partices are not optimized, perhaps the types of data do not stretch, etc.

**Comment by Swartz27** [comment]
I guess what I'm getting at is this is not a proper x64 repo, something is wrong with it.
I reccomend porting your changes to the latest lm-dex repo. His doesn't have these problems, and you're based off him anyway, why not use the latest code?
If not it's all good, but I guess I'm just surprised that it was never tested that this used more than 4gb as thats kinda the point of x64...

**Comment by ForserX** [comment]
@Swartz27, Repositories are too different, so there will not be any transfer. Initially, the repository was made under the original game, on which everything works.
