### ISSUE TITLE
LINK : fatal error LNK1104: не удается открыть файл "opc.lib"

### ISSUE THREAD

**Issue by DaaGuda** [ForserX/xray-oxygen#21]
При сборке xrCDB получается вот такое: 

1>------ Сборка начата: проект: xrCDB, Конфигурация: Debug Win32 ------
1>LINK : fatal error LNK1104: не удается открыть файл "opc.lib"
1>Сборка проекта "xrCDB.vcxproj" завершена с ошибкой.
========== Сборка: успешно: 0, с ошибками: 1, без изменений: 3, пропущено: 0 ==========

**Comment by ForserX** [comment]
1. Ставь Release(Если есть поддержка AVX, иначе Release_AI32) и x64. 
1. Сбилди OpenCode
