### ISSUE TITLE
Immediate CTD when using Release Binaries

### ISSUE THREAD

**Issue by Derranged** [ForserX/xray-oxygen#55]
Hello, sorry if this is the wrong way to go about reporting these kind of issues however when attempting to use the release binaries the game will CTD.

Here is the log:
[[12.12.2017 13.27.51].log](https://github.com/ForserX/xray-oxygen/files/1550155/12.12.2017.13.27.51.log)

I have tried a few things to fix this however haven't been able to get it working. I am also using the Steam version as my original CD has cracks due to the case.

Thanks.

**Comment by ForserX** [comment]
Your COP is English version?

**Comment by Derranged** [comment]
Yes it is.

**Comment by Derranged** [comment]
I just changed the localization to Russian and it worked straight away! Is there any engine mods that restrict this or can I fix this by changing files in gamedata?

**Comment by ForserX** [comment]
Transfer the changes from ui_st_loadscreen.xml to the English version. There are removed tips with mp keys. If you send PR, I will be grateful.

**Comment by Derranged** [comment]
I have merged both together however the crash persists when changed back to English localization.

Here's the modified files if you would like to test, I have used software to check for differences between the Russian and English files and they appear to be correct.
[eng.zip](https://github.com/ForserX/xray-oxygen/files/1550493/eng.zip)

**Comment by Derranged** [comment]
Ok I fixed that issue, sorry I made a mistake.
Here's the fixed version that does work.
[eng.zip](https://github.com/ForserX/xray-oxygen/files/1550606/eng.zip)

However I had a crash when Unloading ammo from a gun, whatever the characters are in the crash are in Russian and are broken as my computer cannot read it.
[[12.12.2017 17.15.26].log](https://github.com/ForserX/xray-oxygen/files/1550618/12.12.2017.17.15.26.log)

**Comment by Derranged** [comment]
I am also crashing when loading saves 
[[12.12.2017 17.38.04].log](https://github.com/ForserX/xray-oxygen/files/1550658/12.12.2017.17.38.04.log)

**Comment by ForserX** [comment]
I know, WIP.

**Comment by ForserX** [comment]
Now everything is all right. There will be bugs, make a new request.
