### ISSUE TITLE
Random CTD

### ISSUE THREAD

**Issue by Derranged** [ForserX/xray-oxygen#58]
I have been having this issue while bug finding, there appears to be no obvious trigger and happens anywhere on the map.

[[14.12.2017 09.13.41].log](https://github.com/ForserX/xray-oxygen/files/1557454/14.12.2017.09.13.41.log)
[[14.12.2017 09.04.40].log](https://github.com/ForserX/xray-oxygen/files/1557436/14.12.2017.09.04.40.log)
[[13.12.2017 14.34.45].log](https://github.com/ForserX/xray-oxygen/files/1557437/13.12.2017.14.34.45.log)

Also there appears to be an issue when using a Scope or Binoculars, the players hands are being rendered.

**Comment by Derranged** [comment]
Just had another random CTD when talking to a Stalker.
[[14.12.2017 11.37.49].log](https://github.com/ForserX/xray-oxygen/files/1557672/14.12.2017.11.37.49.log)

**Comment by ForserX** [comment]
Which commit are you using?

**Comment by Derranged** [comment]
I am using your latest release version, I haven't compiled any myself.

**Comment by ForserX** [comment]
@Derranged,
